services:
  db:
    # image: postgres:15
    build:
      context: .
      dockerfile: dev/postgres/Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5400:5432'

volumes:
  db_data:
