FROM postgres:15
WORKDIR /docker-entrypoint-initdb.d/

# RUN echo "CREATE ROLE supabase_admin superuser;" \
#   "CREATE ROLE pgbouncer superuser;" \
#   "CREATE USER pgbouncer;" > 1-create-user.sql
# COPY db-backup/backup.sql 2-database.sql
